site_name: 十元建立的世界觀
theme:
  name: material
  language: zh-Hant  # 設定為繁體中文（搜尋介面也會變中文）
  palette: 
    # 日夜模式切換按鈕
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切換至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切換至淺色模式
  features:
    - content.tabs.link
    - navigation.tags  # 在側邊欄顯示標籤（可選）
    - navigation.tabs      # 頂部導航欄（適合大分類）
    - navigation.sections  # 側邊欄分組標題
    - navigation.expand    # 預設展開所有目錄
    - search.suggest       # 搜尋自動補完
    - content.code.copy    # 程式碼右上角出現複製按鈕

plugins:
  - search
  - tags:
      tags_file: tags.md  # 指定 tags 的檔案路徑
markdown_extensions:
  - admonition          # 提醒區塊
  - pymdownx.details    # 折疊區塊
  - pymdownx.arithmatex: # LaTeX
      generic: true  
  - pymdownx.tabbed:    # 標籤頁
      alternate_style: true 
  - footnotes           # 腳註
  - tables              # 表格
  - attr_list           # 允許為元素加入 CSS 類別
  - pymdownx.mark       # 螢光筆文字
  - pymdownx.tilde      # 刪除線
  - pymdownx.superfences: # 支持嵌套語法（如標籤頁裡放代碼）
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # 使用標準格式而非 mermaid_format
nav:
  - 首頁: index.md
  - 定居地:
    - I.小村莊:
      - 001 藻林村: settlement/hamlet/001.藻林村.md
    - II.村莊:
      - 001 劍貝港: settlement/village/001.劍貝港.md
    - III.小鎮:
      - 001 紅流: settlement/town/001.紅流.md
    - IV.城市:
      - 001 陣列岩: settlement/city/001.陣列岩.md
    - V.首都:
      - 001 長灣: settlement/capital/001.長灣.md
  - 地下城:
    - I.小型(Small): 
      - 海蝕洞: dungeon/small/海蝕洞.md
    - II.中型(Medium):
      - 施工中: 404.md
    - III.大型(Large):
      - 施工中: 404.md
extra_javascript:
  - javascripts/mermaid.js  # 放在本地的初始化腳本
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js