site_name: 十元建立的世界觀
theme:
  name: material
  language: zh-Hant  # 設定為繁體中文（搜尋介面也會變中文）
  palette: 
    # 日夜模式切換按鈕
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切換至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切換至淺色模式
  features:
    - content.tabs.link
    - navigation.tags  # 在側邊欄顯示標籤（可選）
    - navigation.tabs      # 頂部導航欄（適合大分類）
    - navigation.sections  # 側邊欄分組標題
    - navigation.expand    # 預設展開所有目錄
    - search.suggest       # 搜尋自動補完
    - content.code.copy    # 程式碼右上角出現複製按鈕

plugins:
  - search
  - tags:
      tags_file: tags.md  # 指定 tags 的檔案路徑
markdown_extensions:
  - admonition          # 提醒區塊
  - pymdownx.details    # 折疊區塊
  - pymdownx.tabbed:    # 標籤頁
      alternate_style: true 
  - footnotes           # 腳註
  - tables              # 表格
  - attr_list           # 允許為元素加入 CSS 類別
  - pymdownx.superfences: # 支持嵌套語法（如標籤頁裡放代碼）
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # 使用標準格式而非 mermaid_format
nav:
  - 首頁: index.md
  - 市鎮:
    - 小村莊(Hamlet):
      - 藻林村: hamlet/藻林村.md
    - 村莊(Village): 404.md
    - 小鎮(Town): 404.md
    - 城市(City): 404.md
    - 首都(Capital): 404.md
  - 地下城:
    - 小型(Small): 404.md
    - 中型(Medium): 404.md
    - 大型(Large): 404.md
extra_javascript:
  - javascripts/mermaid.js  # 放在本地的初始化腳本
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js