name: publish site
on:
  push:
    branches:
      - main  # 當 main 分支有更新時觸發
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install --upgrade mkdocs-material pymdown-extensions
      - run: mkdocs gh-deploy --force